baseURL = 'https://git.ajune.cn/'
languageCode = 'en-us'
title = 'AJUNE的个人空间'
theme = "PaperMod"
# disableKinds = ['taxonomy', 'term']
# 启用 Hugo 资源压缩（minify）
[minify]
	disableXML = false
	minifyOutput = true
	[minify.tdewolff]
		[minify.tdewolff.html]
			keepWhitespace = false
		[minify.tdewolff.css]
			version = 2
		[minify.tdewolff.js]
			keepVarNames = false

[[menu.main]]
	identifier = "home"
	name = "主页"
	url = "/"
	weight = 1

[[menu.main]]
	identifier = "projects"
	name = "项目"
	url = "/projects/"
	weight = 2

[[menu.main]]
	identifier = "posts"
	name = "文章"
	url = "/posts/"
	weight = 3

[[menu.main]]
	identifier = "about"
	name = "关于"
	url = "/about/"
	weight = 4

[[menu.main]]
	identifier = "examples"
	name = "例子"
	url = "/examples/"
	weight = 5