baseURL = 'https://git.ajune.cn/'
languageCode = 'en-us'
title = 'AJUNE的个人空间'
theme = "PaperMod"

[[menu.main]]
	identifier = "home"
	name = "主页"
	url = "/"
	weight = 1

[[menu.main]]
	identifier = "projects"
	name = "项目"
	url = "/projects/"
	weight = 2

[[menu.main]]
	identifier = "posts"
	name = "文章"
	url = "/posts/"
	weight = 3

[[menu.main]]
	identifier = "about"
	name = "关于"
	url = "/about/"
	weight = 4

[[menu.main]]
	identifier = "apps"
	name = "例子"
	url = "/apps/"
	weight = 5

[params]
	defaultTheme = "dark"